export const AUDIOS_JOKE = [
  { label: '¿Isidora?', file: 'Isidora.mp3' },
  { label: '¿Ehh?', file: 'ehh.mp3' },
  { label: '¡¿Que?!', file: 'que1.mp3' },
  { label: '¿Quee?', file: 'que2.mp3' },
  { label: 'Sí, ¿Quien es?', file: 'sii-quien-es.mp3' },
  { label: 'Yah', file: 'yaa.mp3' },
  { label: 'No', file: 'no.mp3' },
  { label: 'Pero como que', file: 'pero-como-que.mp3' },
  { label: '¿Usté, Usté, Usté quien es digame?', file: 'usted-usted-usted-quien-es-digame.mp3' },
  { label: 'Sii, ese numero es aquí', file: 'sii-ese-numero-es-aqui.mp3' },
  { label: 'Vive aquí, sí', file: 'vive-aqui-si.mp3' },
  { label: '¿Yo? Pero, ¿usté quien es?', file: 'yo-pero-usted-quien-es.mp3' },
  { label: 'Yo soy hermana de Isidora', file: 'yoo-soy-hermana-de-isidora.mp3' },
  { label: '¿Pero usté, usté qué es?', file: 'pero-usted-usted-que-es.mp3' },
  { label: 'Si, ¿Y que es lo que quiere digame?', file: 'si-y-que-es-lo-que-quiere-digame.mp3' },
  { label: '¿Usted a que numero llama?', file: 'usted-a-que-numero-llama.mp3' },
  { label: '¿Yo? Creo que no', file: 'yoo-creo-que-no.mp3' },
  { label: 'Espere un momento', file: 'espere-un-momento.mp3' },
  { label: 'No lo sé', file: 'no-lo-se.mp3' },
  { label: 'No si no me explica otra cosa', file: 'no-si-no-me-explica-otra-cosa.mp3' },
  { label: 'Pero, ¿Isidora no ha llamado a ningún sitio?', file: 'pero-isidora-no-ha-llamado-a-ningun-sitio.mp3' },
  { label: 'Pero, ¿No ha llamado ella a ningún sitio?', file: 'pero-no-ha-llamado-ella-a-ningun-sitio.mp3' },
  { label: 'Pues yo no sé', file: 'pues-yo-no-se.mp3' },
  { label: 'Es un desmadre a la americana!', file: 'es-un-desmadre-a-la-americana.mp3' },
  { label: 'Ya no sé si es a la americana o a la inglesa', file: 'ya-no-se-si-es-a-la-americana-o-a-la-inglesa.mp3' },
  { label: 'Debe ser una confusión mire, no sé como ha podido ser', file: 'debe-ser-una-confusion-mire-no-se-como-ha-podido-ser.mp3' }
]
